{% set version = "0.20.1" %}

package:
  name: gersemi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gersemi/gersemi-{{ version }}.tar.gz
  sha256: acc33a7fba81e13a9feb1db5f57fe8ef65a3814a62b2ad5f4aec1e1df0e8d981

build:
  entry_points:
    - gersemi = gersemi.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - appdirs
    - lark
    - pyyaml

test:
  imports:
    - gersemi
  commands:
    - pip check
    - gersemi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BlankSpruce/gersemi
  summary: A formatter to make your CMake code the real treasure
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
