schema_version: 1

context:
  version: "0.25.1"

package:
  name: gersemi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gersemi/gersemi-${{ version }}.tar.gz
  sha256: a119f5ff0c5133b25e72a5c39f7722535741cb311f66ae17bf1aaf1d1190751a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gersemi = gersemi.__main__:main

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - appdirs
    - lark
    - platformdirs
    - pyyaml

tests:
  - python:
      imports:
        - gersemi
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check
      - gersemi --help

about:
  summary: A formatter to make your CMake code the real treasure
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/BlankSpruce/gersemi

extra:
  recipe-maintainers:
    - danielnachun
