schema_version: 1

context:
  version: "0.25.0"

package:
  name: gersemi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gersemi/gersemi-${{ version }}.tar.gz
  sha256: 5b19c70f5e9e575127ca019ecc13d1c61ca59cbddbebd0688ce08864c0d7f67b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gersemi = gersemi.__main__:main

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - appdirs
    - lark
    - platformdirs
    - pyyaml

tests:
  - python:
      imports:
        - gersemi
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check
      - gersemi --help

about:
  summary: A formatter to make your CMake code the real treasure
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/BlankSpruce/gersemi

extra:
  recipe-maintainers:
    - danielnachun
